GET  http://localhost:3001/api/notes

###

POST http://localhost:3001/api/users
Content-Type: application/json
{
    "username":"root",
    "name":"root",
    "password":"root"
}

###
GET http://localhost:3001/api/users

###
GET http://localhost:3001/api/notes/65098a39ee846e032021a7e2

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"testeee",
    "important":true
}

###

DELETE http://localhost:3001/api/notes/650ab0c1c2c70ff4bbb65205

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "name":"lelelele",
    "number":655655565
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"prueba",
    "important":true
}

###

DELETE http://localhost:3001/api/notes/64e4ceca47f61aebd5466234

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"prua",
    "important":false
}