GET  http://localhost:3001/api/notes

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"root",
    "password":"root"
}
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username":"root",
    "name":"root",
    "password":"root"
}

###
GET http://localhost:3001/api/users

###
GET http://localhost:3001/api/notes/65098a39ee846e032021a7e2

###

POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1MWMxNjNkMWZlYmY5Mjg5M2YzNTQ0ZCIsImlhdCI6MTY5NzAxMzMwNH0.qXft6Z42MnYyLTtYvFjX_m6bUWvYpEaaumtF71EAzo0

{
    "content":"testeee2",
    "important":true
}

###

DELETE http://localhost:3001/api/notes/650ab0c1c2c70ff4bbb65205

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "name":"lelelele",
    "number":655655565
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"prueba",
    "important":true
}

###

DELETE http://localhost:3001/api/notes/64e4ceca47f61aebd5466234

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"prua",
    "important":false
}